version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - devcontainer-vscode-server:/home/vscode/.vscode-server
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
      - MIX_ENV=dev
    ports:
      - "3000:3000"  # Python Flask/FastAPI
      - "4000:4000"  # Elixir Phoenix
      - "8000:8000"  # Rust web server
    stdin_open: true
    tty: true

volumes:
  devcontainer-vscode-server: